[versions]
mod-version = "0.1.0"

# Fabric & Minecraft versions
minecraft = "1.21.8"
yarn-mappings = "1.21.8-rc1+build.2"
fabric-loader = "0.17.2"

# Loom for development
loom = "1.14.10"


# Meteor Client snapshot
meteor = "1.21.8-69"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
